import Foundation
import Combine

/// Owns the family graph: Members + Relationships + Devices + the local
/// account. Persisted to UserDefaults; CloudKit family-shared in Build 13.
@MainActor
final class FamilyStore: ObservableObject {
    static let shared = FamilyStore()

    @Published var family: Family
    @Published var members: [Member]
    @Published var relationships: [Relationship]
    @Published var devices: [Device]
    @Published var account: Account

    private static let familyKey = "halowalk.family.v2"
    private static let membersKey = "halowalk.members.v2"
    private static let relationshipsKey = "halowalk.relationships.v2"
    private static let devicesKey = "halowalk.devices.v2"
    private static let accountKey = "halowalk.account.v2"

    init() {
        let dec = JSONDecoder()
        if let fd = UserDefaults.standard.data(forKey: Self.familyKey),
           let f = try? dec.decode(Family.self, from: fd),
           let md = UserDefaults.standard.data(forKey: Self.membersKey),
           let m = try? dec.decode([Member].self, from: md),
           let rd = UserDefaults.standard.data(forKey: Self.relationshipsKey),
           let r = try? dec.decode([Relationship].self, from: rd),
           let dd = UserDefaults.standard.data(forKey: Self.devicesKey),
           let d = try? dec.decode([Device].self, from: dd),
           let ad = UserDefaults.standard.data(forKey: Self.accountKey),
           let a = try? dec.decode(Account.self, from: ad) {
            self.family = f
            // Run name migration first (Build 22), then the Build 26
            // avatar backfill on top — seed members get their seeded
            // avatars even though they were stored before avatarId existed.
            let renamed = Self.migrateBuild22Names(m)
            self.members = Self.migrateBuild26AvatarBackfill(renamed)
            self.relationships = r
            self.devices = Self.migrateBuild22DeviceNames(d)
            self.account = a
            // Save back any in-place rewrites from the migrations.
            let enc = JSONEncoder()
            UserDefaults.standard.set(try? enc.encode(self.members), forKey: Self.membersKey)
            UserDefaults.standard.set(try? enc.encode(self.devices), forKey: Self.devicesKey)
        } else {
            // Schema changed in Build 12a — fall back to seed.
            self.family = MockData.family
            self.members = MockData.allMembers
            self.relationships = MockData.allRelationships
            self.devices = MockData.allDevices
            self.account = MockData.myAccount
            save()
        }
    }

    /// Build 22 renamed the seed user from "Tiger Wong" to "Chelsea Huang".
    /// Existing installs still have the original name in UserDefaults — this
    /// rewrites the seed Member if the stored name still looks
    /// auto-generated. Anything that doesn't start with "Tiger" is treated
    /// as user-edited and left alone.
    private static func migrateBuild22Names(_ stored: [Member]) -> [Member] {
        let tigerId = MockData.tigerId
        return stored.map { m in
            guard m.id == tigerId else { return m }
            let looksAutoGenerated =
                m.name.hasPrefix("Tiger") ||
                m.displayName.hasPrefix("Tiger") ||
                m.name.isEmpty
            guard looksAutoGenerated else { return m }
            var updated = m
            updated.name = MockData.tiger.name
            updated.displayName = MockData.tiger.displayName
            updated.initial = MockData.tiger.initial
            updated.pronouns = MockData.tiger.pronouns
            updated.accentColorHex = MockData.tiger.accentColorHex
            return updated
        }
    }

    /// Build 26: backfill `avatarId` for seed members whose stored record
    /// predates the avatar field. We DON'T blanket-assign to every member
    /// — that would override a deliberate user pick from Build 25. We
    /// only fill in when the seed member's avatarId is still nil AND the
    /// member id matches a known seed.
    private static func migrateBuild26AvatarBackfill(_ stored: [Member]) -> [Member] {
        let seedAvatars: [UUID: String] = [
            MockData.tigerId:  MockData.tiger.avatarId  ?? "",
            MockData.audreyId: MockData.audrey.avatarId ?? "",
            MockData.andrewId: MockData.andrew.avatarId ?? "",
            MockData.mayaId:   MockData.maya.avatarId   ?? "",
            MockData.louId:    MockData.lou.avatarId    ?? "",
        ]
        return stored.map { m in
            // Already has one — respect user's pick.
            if m.avatarId != nil { return m }
            // Not a seed member — leave nil so the picker shows the
            // initial-in-circle fallback and prompts them to choose.
            guard let backfill = seedAvatars[m.id], !backfill.isEmpty else { return m }
            var updated = m
            updated.avatarId = backfill
            return updated
        }
    }

    /// Same thing for the seed devices keyed off the renamed member.
    private static func migrateBuild22DeviceNames(_ stored: [Device]) -> [Device] {
        return stored.map { d in
            guard d.memberId == MockData.tigerId else { return d }
            var updated = d
            if updated.displayName.hasPrefix("Tiger's") {
                updated.displayName = updated.displayName
                    .replacingOccurrences(of: "Tiger's", with: "Chelsea's")
            }
            return updated
        }
    }

    private func save() {
        let enc = JSONEncoder()
        UserDefaults.standard.set(try? enc.encode(family), forKey: Self.familyKey)
        UserDefaults.standard.set(try? enc.encode(members), forKey: Self.membersKey)
        UserDefaults.standard.set(try? enc.encode(relationships), forKey: Self.relationshipsKey)
        UserDefaults.standard.set(try? enc.encode(devices), forKey: Self.devicesKey)
        UserDefaults.standard.set(try? enc.encode(account), forKey: Self.accountKey)
    }

    // MARK: - Read helpers

    var me: Member? {
        members.first { $0.id == account.memberId }
    }
    func member(_ id: UUID) -> Member? {
        members.first { $0.id == id }
    }
    func displayName(_ id: UUID?) -> String {
        guard let id else { return "—" }
        return member(id)?.displayName ?? "—"
    }

    // MARK: - Role inference (from relationships, not stored on Member)

    /// Members this Member watches over (= they're a guardian to these).
    func watches(by memberId: UUID) -> [Member] {
        let watchedIds = relationships
            .filter { $0.watcherId == memberId }
            .map(\.watchedId)
        return members.filter { watchedIds.contains($0.id) }
    }

    /// Members watching over this Member (= their guardians).
    func watchers(of memberId: UUID) -> [Member] {
        let watcherIds = relationships
            .filter { $0.watchedId == memberId }
            .map(\.watcherId)
        return members.filter { watcherIds.contains($0.id) }
    }

    func isGuardian(_ memberId: UUID) -> Bool { !watches(by: memberId).isEmpty }
    func isWatched(_ memberId: UUID) -> Bool { !watchers(of: memberId).isEmpty }

    /// All Members who are watched by anyone (i.e. "wearers" in the old sense).
    var watchedMembers: [Member] {
        let ids = Set(relationships.map(\.watchedId))
        return members.filter { ids.contains($0.id) }
    }
    /// All Members who watch anyone (i.e. "guardians" in the old sense).
    var watcherMembers: [Member] {
        let ids = Set(relationships.map(\.watcherId))
        return members.filter { ids.contains($0.id) }
    }

    // MARK: - Devices

    func devices(for memberId: UUID) -> [Device] {
        devices.filter { $0.memberId == memberId }
    }

    // MARK: - Mutations

    func updateMember(_ member: Member) {
        if let i = members.firstIndex(where: { $0.id == member.id }) {
            members[i] = member
            save()
        }
    }

    /// Build A: stamp the Sign in with Apple identity onto the local
    /// account. Apple only hands over name/email on the *first* sign-in,
    /// so we only overwrite when we actually receive a value. If the local
    /// member still has a placeholder name and Apple gave us a real one,
    /// adopt it (one-time, doesn't clobber a user-edited name).
    func linkAppleIdentity(userId: String, fullName: String?, email: String?) {
        account.appleUserId = userId
        if let email, !email.isEmpty {
            account.email = email
        }
        if let fullName, !fullName.isEmpty,
           let i = members.firstIndex(where: { $0.id == account.memberId }) {
            let current = members[i].name.trimmingCharacters(in: .whitespaces)
            let looksPlaceholder =
                current.isEmpty ||
                current == "Tiger Wong" ||
                current.hasPrefix("Tiger")
            if looksPlaceholder {
                members[i].name = fullName
                if members[i].displayName.isEmpty || members[i].displayName.hasPrefix("Tiger") {
                    members[i].displayName = fullName
                        .split(separator: " ").first.map(String.init) ?? fullName
                }
            }
        }
        save()
    }
    func addMember(_ member: Member) {
        members.append(member)
        family.memberIds.append(member.id)
        save()
    }

    // MARK: - CloudKit merge (Build B)
    // Idempotent upserts called by HaloCloudSync when records arrive from
    // the cloud. Last-writer-wins: the incoming record replaces the local
    // one wholesale. HaloCloudSync sets its `applyingRemoteChanges` guard
    // around these so the @Published change doesn't bounce back up.

    func upsertFromCloud(member: Member) {
        if let i = members.firstIndex(where: { $0.id == member.id }) {
            members[i] = member
        } else {
            members.append(member)
            if !family.memberIds.contains(member.id) {
                family.memberIds.append(member.id)
            }
        }
        save()
    }
    func upsertFromCloud(relationship: Relationship) {
        if let i = relationships.firstIndex(where: { $0.id == relationship.id }) {
            relationships[i] = relationship
        } else {
            relationships.append(relationship)
        }
        save()
    }
    func upsertFromCloud(device: Device) {
        if let i = devices.firstIndex(where: { $0.id == device.id }) {
            devices[i] = device
        } else {
            devices.append(device)
        }
        save()
    }
    func upsertFromCloud(family incoming: Family) {
        // Don't clobber a non-empty local memberIds with an empty cloud
        // one during early bootstrap races.
        var merged = incoming
        if merged.memberIds.isEmpty { merged.memberIds = family.memberIds }
        family = merged
        save()
    }
    func removeMember(_ id: UUID) {
        members.removeAll { $0.id == id }
        family.memberIds.removeAll { $0 == id }
        relationships.removeAll { $0.watcherId == id || $0.watchedId == id }
        devices.removeAll { $0.memberId == id }
        save()
    }
    func replaceAll(members newMembers: [Member]) {
        members = newMembers
        save()
    }
    func resetToDemo() {
        family = MockData.family
        members = MockData.allMembers
        relationships = MockData.allRelationships
        devices = MockData.allDevices
        account = MockData.myAccount
        save()
    }

    func addRelationship(_ r: Relationship) {
        relationships.append(r)
        save()
    }
    func removeRelationship(_ id: UUID) {
        relationships.removeAll { $0.id == id }
        save()
    }

    func addDevice(_ d: Device) {
        devices.append(d)
        save()
    }
    func updateDevice(_ d: Device) {
        if let i = devices.firstIndex(where: { $0.id == d.id }) {
            devices[i] = d
            save()
        }
    }
    func removeDevice(_ id: UUID) {
        devices.removeAll { $0.id == id }
        save()
    }
}
