import Foundation
import CoreLocation
import Combine

/// Persistent hub list, scoped to the family. Build 13 will swap
/// UserDefaults for a CloudKit shared zone so hubs sync between guardians.
@MainActor
final class HubStore: ObservableObject {
    static let shared = HubStore()

    @Published var hubs: [Hub] = []
    @Published var corridors: [Corridor] = []

    private static let hubsKey = "halowalk.hubs.v3"
    private static let corridorsKey = "halowalk.corridors.v3"

    init() { load() }

    private func load() {
        let dec = JSONDecoder()
        if let hd = UserDefaults.standard.data(forKey: Self.hubsKey),
           let parsed = try? dec.decode([Hub].self, from: hd) {
            hubs = Self.dedupeHomes(Self.migrateBuild16Coordinates(parsed))
        } else {
            hubs = MockData.allHubs
        }
        if let cd = UserDefaults.standard.data(forKey: Self.corridorsKey),
           let parsed = try? dec.decode([Corridor].self, from: cd) {
            corridors = parsed
        } else {
            corridors = MockData.allCorridors
        }
        save()
    }

    /// Build 12–15 shipped seed hubs with placeholder lat/lon that didn't
    /// match the addresses. Build 16 fixes the seed coordinates. Any
    /// installed hub whose id matches a seed AND whose stored lat/lon
    /// still matches the OLD (wrong) seed values gets silently updated to
    /// the new correct coordinates. Hubs the user moved/customized won't
    /// match the old values exactly, so they're left alone.
    private static let oldSeedCoordinates: [UUID: (lat: Double, lon: Double)] = [
        UUID(uuidString: "33333333-3333-3333-3333-000000000001")!: (37.5202, -122.2758), // Home
        UUID(uuidString: "33333333-3333-3333-3333-000000000002")!: (37.5172, -122.2843), // Cipriani
        UUID(uuidString: "33333333-3333-3333-3333-000000000003")!: (37.5157, -122.2880), // Ralston
        UUID(uuidString: "33333333-3333-3333-3333-000000000004")!: (37.5146, -122.2784), // Carlmont
        UUID(uuidString: "33333333-3333-3333-3333-000000000005")!: (37.5208, -122.2756), // Library
        UUID(uuidString: "33333333-3333-3333-3333-000000000006")!: (37.5195, -122.2786), // Community
        UUID(uuidString: "33333333-3333-3333-3333-000000000007")!: (37.5253, -122.2901), // Grandma
    ]

    /// Build 16–21 had Home seeded at the generic Belmont city centroid
    /// (37.5180, -122.2960) with address "Belmont, CA" — fine as a placeholder
    /// while the user hadn't picked a real home yet. Build 22 relocates the
    /// seed Home to Reposo Way (per the user's actual address). The geocoder
    /// will refine this further on next launch via the seedGeocoded.v3 flag.
    private static let homeBelmontCentroid: (lat: Double, lon: Double) = (37.5180, -122.2960)

    /// Pre-Build-22 Home addresses we know we autogenerated. If the stored
    /// address matches one of these verbatim, the user almost certainly
    /// hasn't edited it themselves and we can safely overwrite to the new
    /// precise mid-block address.
    private static let preBuild22HomeAddresses: Set<String> = [
        "Reposo Way, Belmont, CA",
        "Belmont, CA",
        "Belmont, CA, USA"
    ]

    private static func migrateBuild16Coordinates(_ stored: [Hub]) -> [Hub] {
        let newById = Dictionary(uniqueKeysWithValues: MockData.allHubs.map { ($0.id, $0) })
        let homeId = UUID(uuidString: "33333333-3333-3333-3333-000000000001")!
        return stored.map { hub in
            // Build 22: relocate Home to mid-Reposo Way.
            // We accept the migration if EITHER the stored coords still
            // match an old auto-seeded value OR the address is one we
            // know we generated automatically (i.e. not user-edited).
            if hub.id == homeId, let newSeed = newById[homeId] {
                let trimmedAddress = hub.address.trimmingCharacters(in: .whitespaces)
                let matchesCentroid =
                    abs(hub.latitude - homeBelmontCentroid.lat) < 0.0001 &&
                    abs(hub.longitude - homeBelmontCentroid.lon) < 0.0001
                let matchesOldHomeSeed =
                    oldSeedCoordinates[homeId].map { old in
                        abs(hub.latitude - old.lat) < 0.0001 &&
                        abs(hub.longitude - old.lon) < 0.0001
                    } ?? false
                let addressLooksAutoGenerated =
                    preBuild22HomeAddresses.contains(trimmedAddress)
                if matchesCentroid || matchesOldHomeSeed || addressLooksAutoGenerated {
                    var migrated = hub
                    migrated.latitude = newSeed.latitude
                    migrated.longitude = newSeed.longitude
                    migrated.address = newSeed.address
                    return migrated
                }
            }
            // Build 16 fixup of hand-typed seed coords for non-Home hubs.
            guard
                let oldCoord = oldSeedCoordinates[hub.id],
                let newSeed = newById[hub.id],
                abs(hub.latitude - oldCoord.lat) < 0.0001,
                abs(hub.longitude - oldCoord.lon) < 0.0001
            else { return hub }
            var migrated = hub
            migrated.latitude = newSeed.latitude
            migrated.longitude = newSeed.longitude
            return migrated
        }
    }

    private func save() {
        let enc = JSONEncoder()
        UserDefaults.standard.set(try? enc.encode(hubs), forKey: Self.hubsKey)
        UserDefaults.standard.set(try? enc.encode(corridors), forKey: Self.corridorsKey)
    }

    func replaceAll(hubs newHubs: [Hub]) { hubs = newHubs; save() }

    func add(_ hub: Hub) { hubs.append(hub); save() }
    func update(_ hub: Hub) {
        if let i = hubs.firstIndex(where: { $0.id == hub.id }) {
            hubs[i] = hub; save()
        }
    }
    func remove(_ id: UUID) {
        hubs.removeAll { $0.id == id }
        corridors.removeAll { $0.fromHubId == id || $0.toHubId == id }
        save()
    }

    /// CloudKit merge (Build B). Idempotent last-writer-wins upsert called
    /// by HaloCloudSync; the engine's `applyingRemoteChanges` guard keeps
    /// this from bouncing back up.
    func upsertFromCloud(hub: Hub) {
        if let i = hubs.firstIndex(where: { $0.id == hub.id }) {
            hubs[i] = hub
        } else {
            hubs.append(hub)
        }
        // A duplicate "Home" arriving from the cloud (left over from the
        // old re-onboarding bug) must not re-pollute. Re-run the same
        // dedupe and record the loser so the sync layer can delete it
        // from CloudKit too.
        if hub.name == "Home", hubs.filter({ $0.name == "Home" }).count > 1 {
            let before = Set(hubs.map(\.id))
            hubs = Self.dedupeHomes(hubs)
            let removed = before.subtracting(hubs.map(\.id))
            Self.homesPrunedFromCloud.append(contentsOf: removed)
        }
        save()
    }

    /// Hubs assigned to any of the given Members. Empty input = all hubs.
    func hubs(forMembers memberIds: Set<UUID>) -> [Hub] {
        if memberIds.isEmpty { return hubs }
        return hubs.filter { hub in
            hub.assignedMemberIds.isEmpty ||
            !Set(hub.assignedMemberIds).intersection(memberIds).isEmpty
        }
    }

    /// Canonical Home id — the MockData seed Home. Onboarding updates
    /// THIS hub in place rather than dropping new ones.
    private static let canonicalHomeId = MockData.homeId

    /// Build 35: collapse duplicate "Home" hubs accumulated by repeated
    /// reinstall → re-onboarding (each old onboarding dropped a fresh
    /// Home with a random UUID). Keep the canonical seed Home if present,
    /// else the oldest; drop the rest. The dropped ids are recorded so
    /// the sync layer can also delete them from CloudKit.
    static var homesPrunedFromCloud: [UUID] = []

    private static func dedupeHomes(_ input: [Hub]) -> [Hub] {
        let homes = input.filter { $0.name == "Home" }
        guard homes.count > 1 else { return input }
        // Prefer the canonical seed; otherwise the earliest-created.
        let keeper = homes.first { $0.id == canonicalHomeId }
            ?? homes.sorted { $0.createdAt < $1.createdAt }.first!
        let dropped = homes.filter { $0.id != keeper.id }
        homesPrunedFromCloud.append(contentsOf: dropped.map(\.id))
        let droppedIds = Set(dropped.map(\.id))
        return input.filter { !droppedIds.contains($0.id) }
    }

    /// Idempotent "drop your first halo." Updates the canonical Home's
    /// coordinate if it exists (no duplicate), else creates it once.
    func setHomeToCurrentLocation(
        coordinate: CLLocationCoordinate2D,
        assignedTo memberIds: [UUID],
        createdBy: UUID
    ) {
        if let i = hubs.firstIndex(where: { $0.name == "Home" }) {
            hubs[i].latitude = coordinate.latitude
            hubs[i].longitude = coordinate.longitude
            if hubs[i].assignedMemberIds.isEmpty {
                hubs[i].assignedMemberIds = memberIds
            }
            save()
        } else {
            _ = dropHubAtCurrentLocation(
                named: "Home", icon: "⌂", coordinate: coordinate,
                haloMeters: 80, colorHex: 0x5A9D6E,
                assignedTo: memberIds, createdBy: createdBy
            )
        }
    }

    func dropHubAtCurrentLocation(
        named name: String,
        icon: String,
        coordinate: CLLocationCoordinate2D,
        haloMeters: Double = 80,
        colorHex: UInt32 = 0x5A9D6E,
        assignedTo memberIds: [UUID],
        createdBy: UUID
    ) -> Hub {
        let hub = Hub(
            id: UUID(),
            name: name,
            icon: icon,
            address: "",
            latitude: coordinate.latitude,
            longitude: coordinate.longitude,
            haloRadiusMeters: haloMeters,
            colorHex: colorHex,
            assignedMemberIds: memberIds,
            createdById: createdBy,
            createdAt: Date(),
            notes: nil
        )
        add(hub)
        return hub
    }

    func hubsContaining(_ location: CLLocation, forMember memberId: UUID) -> [Hub] {
        hubs(forMembers: [memberId]).filter { hub in
            location.distance(from: hub.locationObject) <= hub.haloRadiusMeters
        }
    }
    func nearestHub(to location: CLLocation, forMember memberId: UUID) -> (hub: Hub, meters: Double)? {
        let candidates = hubs(forMembers: [memberId])
        var best: (Hub, Double)?
        for h in candidates {
            let d = location.distance(from: h.locationObject)
            if best == nil || d < best!.1 {
                best = (h, d)
            }
        }
        return best.map { (hub: $0.0, meters: $0.1) }
    }

    // MARK: - Backward-compat shims (Build 11 callers using "wearer" naming)

    @available(*, deprecated, renamed: "hubs(forMembers:)")
    func hubs(forWearers ids: Set<UUID>) -> [Hub] { hubs(forMembers: ids) }

    @available(*, deprecated, renamed: "nearestHub(to:forMember:)")
    func nearestHub(to location: CLLocation, forWearer id: UUID) -> (hub: Hub, meters: Double)? {
        nearestHub(to: location, forMember: id)
    }
}

private extension Hub {
    var locationObject: CLLocation {
        CLLocation(latitude: latitude, longitude: longitude)
    }
}

extension HubStore {
    /// One-time pass: forward-geocode the addresses of any seed hub whose
    /// stored coordinates were hand-typed approximations. Updates the
    /// lat/lon to whatever Apple Maps says is the real location of that
    /// address. Skips quietly on offline / rate-limit errors so it can
    /// retry next launch.
    func geocodeSeedHubsIfNeeded() async {
        // Bumped to v4 in Build 22 so existing installs re-geocode Home now
        // that it points at "3608 Reposo Way, Belmont, CA 94002" (a precise
        // mid-block address) instead of the prior end-of-street resolution.
        let flagKey = "halowalk.hubs.seedGeocoded.v4"
        if UserDefaults.standard.bool(forKey: flagKey) { return }

        let geocoder = CLGeocoder()
        let seedIds = Set(MockData.allHubs.map(\.id))
        var allSucceeded = true

        for i in hubs.indices where seedIds.contains(hubs[i].id) {
            let address = hubs[i].address
            // Need a real street address — anything missing a comma+region
            // is too fuzzy ("Belmont, CA" alone resolves to the city center).
            let parts = address.split(separator: ",")
            guard parts.count >= 3 else { continue }

            do {
                // Apple's geocoder is rate-limited (~1 req/sec). Pace.
                try await Task.sleep(nanoseconds: 1_000_000_000)
                let placemarks = try await geocoder.geocodeAddressString(address)
                if let coord = placemarks.first?.location?.coordinate {
                    hubs[i].latitude = coord.latitude
                    hubs[i].longitude = coord.longitude
                }
            } catch {
                // Network down, rate-limited, or address unrecognized.
                // Try again next launch.
                allSucceeded = false
            }
        }

        save()
        if allSucceeded {
            UserDefaults.standard.set(true, forKey: flagKey)
        }
    }
}
